$(document).ready(function(){
  $("#para").hide();
  $("#para0").hide();
  $("#para1").hide();
  $("#para2").hide();
  $("#para3").hide();
  $("#para4").hide();
  $("#para5").hide();
  $("#para6").hide();
  $("#para7").hide();
  $("#para8").hide();
  $("#para9").hide();
  $("#para10").hide();
  $("#para11").hide();
  $("#para12").hide();
  $("#para13").hide();
  $("#para14").hide();
  $("#para15").hide();
  $("#para16").hide();
  $("#para17").hide();
  $("#para18").hide();

  $("#image").hover(function(){
    $("#para").fadeIn();
  },
  function(){
    $("#para").fadeOut();
  });
  $("#image0").hover(function(){
    $("#para0").fadeIn();
  },
  function(){
    $("#para0").fadeOut();
  });
  $("#image1").hover(function(){
    $("#para1").fadeIn();
  },
  function(){
    $("#para1").fadeOut();
  });
  $("#image2").hover(function(){
    $("#para2").fadeIn();
  },
  function(){
    $("#para2").fadeOut();
  });
  $("#image3").hover(function(){
    $("#para3").fadeIn();
  },
  function(){
    $("#para3").fadeOut();
  });
  $("#image4").hover(function(){
    $("#para4").fadeIn();
  },
  function(){
    $("#para4").fadeOut();
  });
  $("#image5").hover(function(){
    $("#para5").fadeIn();
  },
  function(){
    $("#para5").fadeOut();
  });
  $("#image6").hover(function(){
    $("#para6").fadeIn();
  },
  function(){
    $("#para6").fadeOut();
  });
  $("#image7").hover(function(){
    $("#para7").fadeIn();
  },
  function(){
    $("#para7").fadeOut();
  });
  $("#image8").hover(function(){
    $("#para8").fadeIn();
  },
  function(){
    $("#para8").fadeOut();
  });
  $("#image9").hover(function(){
    $("#para9").fadeIn();
  },
  function(){
    $("#para9").fadeOut();
  });
  $("#image10").hover(function(){
    $("#para10").fadeIn();
  },
  function(){
    $("#para10").fadeOut();
  });
  $("#image11").hover(function(){
    $("#para11").fadeIn();
  },
  function(){
    $("#para11").fadeOut();
  });
  $("#image13").hover(function(){
    $("#para13").fadeIn();
  },
  function(){
    $("#para13").fadeOut();
  });
  $("#image14").hover(function(){
    $("#para14").fadeIn();
  },
  function(){
    $("#para14").fadeOut();
  });
  $("#image15").hover(function(){
    $("#para15").fadeIn();
  },
  function(){
    $("#para15").fadeOut();
  });
  $("#image16").hover(function(){
    $("#para16").fadeIn();
  },
  function(){
    $("#para16").fadeOut();
  });
  $("#image17").hover(function(){
    $("#para17").fadeIn();
  },
  function(){
    $("#para17").fadeOut();
  });
  $("#image18").hover(function(){
    $("#para18").fadeIn();
  },
  function(){
    $("#para18").fadeOut();
  });
  $("#image12").hover(function(){
    $("#para12").fadeIn();
  },
  function(){
    $("#para12").fadeOut();
  });

});
